# Generated by Django 4.0.3 on 2022-10-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationvo',
            old_name='import_herf',
            new_name='import_href',
        ),
    ]
